### ISSUE TITLE
end of summer sync

### ISSUE THREAD

**Issue by dckc** [kumc-bmi/nextd-study-support#11]
Brennan, you're off to school after this week, right? Thanks for your contributions to date.

@bconnolly is 4ba0ac2 your latest work? It looks like your last few commits (thru 08a92c7) aren't in PR #9. Perhaps you'd like to submit a PR to replace #9 ? Or are those latest commits WIP or something?

Have you done any work that I wouldn't find easily from your fork? Please summarize. If any of it is not for public consumption, mail it to me, Mei, and Tamara (and, if appropriate, George and Alona).

cc @gkowalski

**Comment by bconnolly** [comment]
I found some files that I had saved but not committed, so I'll see if I can square those away before the day is out. I think the main work that is not easily accessible from the fork is the Jupyter notebook on the quality of the data in Table 1... and possibly some exploration into why lots of geocoded addresses don't match addresses we have in our EHR.

**Comment by bconnolly** [comment]
Looking back, my version control practices were not great. I was always committing and pushing to the master branch... I suppose it was acceptable because it was just my fork, but not the best practice going forward.

**Comment by bconnolly** [comment]
Alright, I pushed some more code (66365c4) to my fork. There is one other file that might be relevant, but it's essentially a 769-line scratchpad that investigates why the geocoded data and hospital records don't have matching addresses. Most of the important findings can be found in comments on KUMC ticket 4735.

As for the Jupyter notebook, I shared the results with Alona and Dan but I am unsure of how to share the code.

**Comment by dckc** [comment]
Your message of Thursday, July 20, 2017 9:50 AM includes an .ipynb attachment. Is there some code that's not in the notebook?

**Comment by dckc** [comment]
OK, I gather I've got all the bits and pieces now. Thanks.

**Comment by bconnolly** [comment]
Ah, I forgot I had attached that. 

All of the code I wrote is now on my fork, in the notebook, or emailed to Dan and Mei.
