### ISSUE TITLE
Finding "The date of the first medication of any kind...for each patient" takes a huge amount of time.

### ISSUE THREAD

**Issue by bconnolly** [kumc-bmi/nextd-study-support#3]
The query that begins "create or replace view each_med_obs as" in NextDvariableExtractionOracleTable1GPC.sql is painfully slow. Running this on our B2 production database, where the PRESCRIBING table has over 62 million rows, produced time estimates over 100 hours. The Oracle plan showed nested loops for PRESCRIBING and the 2676-row nextd-med-info table.

Dan and I tried several changes, such as removing an Oracle hint, breaking up the query into smaller components, and caching the names of the meds of interest. None of it made a significant positive difference in the time estimates.

The quote in the title references a comment just above the query.

**Comment by dckc** [comment]
progress: 276c499

**Comment by dckc** [comment]
Also: our database might have been sick. We restarted it and it's behaving better in various ways now.
